version: "3.9"

services:
  web:
    build: .
    container_name: perpustakaan_web
    restart: unless-stopped
    ports:
      - "6001:5000"
    volumes:
      - ./instance:/app/instance
      - ./static/uploads:/app/static/uploads
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=False
      - DATABASE_URL=sqlite:////app/instance/perpustakaan.db
